### ISSUE TITLE
US 01.05.01 As an experimenter, I want to be able to execute trials for an experiment and upload them to the experiment.

### ISSUE THREAD

**Issue by arrooney** [CMPUT301W21T05/KrowdTrialz#10]

**Comment by FurmaanS** [comment]
##Rationale
Drives requirement for experiment details screen and the trail screens. Allows the user to run/record the results for an experiment. Can provide insight into results of trials.

**Comment by arrooney** [comment]
@FurmaanS I think we don't want to close these yet, since we haven't actually addressed these user stories anywhere.

**Comment by FurmaanS** [comment]
@arrooney I agree
