### ISSUE TITLE
US 01.09.01 As an owner or experimenter, I want to observe statistics (quartiles, median, mean, stdev) about a current trials.

### ISSUE THREAD

**Issue by arrooney** [CMPUT301W21T05/KrowdTrialz#12]

**Comment by FurmaanS** [comment]
## Rationale 
A requirement for experiment details screen. Allows users to visually observe the results of current trials specifically the quartiles, median, mean, stdev. Can provide insight into the pattern of results of the trial.

## TODO
- [ ]
