### ISSUE TITLE
US 01.06.01/US 01.07.01 As an owner or experimenter, I want to see histograms and plot versus time of the results of trials.

### ISSUE THREAD

**Issue by arrooney** [CMPUT301W21T05/KrowdTrialz#13]

**Comment by FurmaanS** [comment]
##  Rationale
A requirement for viewing the results of a recorded experiment. Allows users to view the results of trials for experiments using histograms and plots vs time. Can provide insight into the pattern of trials.

## TODO
- [ ] Figure out how to implement histograms and plots in Android Studio
