### ISSUE TITLE
US 03.01.01 As an experimenter, I want to be able to generate QR codes that I can print for a specific experiment and trial result (for instance PASS for a binomial trial I subscribed to). 

### ISSUE THREAD

**Issue by arrooney** [CMPUT301W21T05/KrowdTrialz#16]

**Comment by rpshukla** [comment]
## Rationale
Experimenters should be able to generate a new QR code so that they can quickly and conveniently enter specific trial results. Allowing the user to create a QR code that corresponds to any trial result gives more flexibility to the user.
