### ISSUE TITLE
US 03.03.01 As an experimenter, I want to be able to register an arbitrary bar code (such as one off of your favourite book) to act a specific experiment result for a trial.

### ISSUE THREAD

**Issue by arrooney** [CMPUT301W21T05/KrowdTrialz#18]

**Comment by Ricky-Au** [comment]
### Rationale
For some experiments an experimenter may want to use barcodes as results for a specific experiment. Allow the experimenter to register a barcode as a specific experiment result 

### TODO

- [ ] Figure out how to scan and store specific barcode in Android Studio
