### ISSUE TITLE
Publish Experiment Screen (tab of homepage):

### ISSUE THREAD

**Issue by Jacques857** [CMPUT301W21T05/KrowdTrialz#37]
Elements:
 -Description, region, minimum trials [Editable]
 -Type of trial radio boxes (Count, Binomial, Non-negative Integer, Measurement)
 -Geo-location required checkbox
 -If count, non-negative integer, or measurement selected:
*Name of measured variable entry field
-If binomial trial selected:
*Name of positive and negative trial result entry fields
-Publish/commit button

**Comment by arrooney** [comment]
![image](https://user-images.githubusercontent.com/33853907/108020970-cbf02a00-6fda-11eb-9199-1bc4f86f7e61.png)
