### ISSUE TITLE
Experiment Details Screen (owner):

### ISSUE THREAD

**Issue by Jacques857** [CMPUT301W21T05/KrowdTrialz#42]
Elements:
  - End experiment button
  - Unpublish button
  - Generate QR code
  - View contributors button
  ...
  - Add trial button
  - Description, region, minimum trials [Editable]
  - Subscribe button
  - Statistics (quartiles, median, mean, stdev)
  - Histogram
  - Plots
  - Q&A button
  - View map button
    * map dialog

**Comment by rpshukla** [comment]
Do we need a "Generate QR code" button on this page? I think we decided to move it to the trials screens and we maybe forgot to remove it from here.

**Comment by Jacques857** [comment]
Yes I think you're right, we don't need a generate QR code button on this screen. Anyone correct me if I'm wrong though.

**Comment by arrooney** [comment]
Right, because the QR code is for a particular outcome of an experiment, so this page isn't specific enough to use to generate the code.
